### ISSUE TITLE
Temp Working Directory Option

### ISSUE THREAD

**Issue by PiDockMedia** [Dapbler/cbr2cbz#16]
Would you add an option to --workingdirectory PATH to allow choosing a directory?

In Mac OS X I make a temporary ramdisk for things like this as /tmp is on the ssd and is a link to /private/tmp which some times causes weirdness.

I am a shell guy and not python or I'd fork and add it myself.

**Comment by Dapbler** [comment]
I was just thinking about adding that in (with regard to the other MacOS temp issue). Maybe coincidence or maybe I saw this note in an e-mail and forgot.

Whatever system I originally wrote this script for had /tmp as tmpfs, but my current one doesn't. An option for setting a temp area is the easiest way I think.

**Comment by Dapbler** [comment]
Consolidating into #15

**Comment by Dapbler** [comment]
Closing (if I hit the right button this time...)
